baseurl = "https://drewkhoury.github.io/communities/"
languageCode = "en-us"
title = "Communities"
theme = "hugo-cards"
themesDir = "./themes/"
paginate = 9

[taxonomies]
  category = 'categories'
  series = 'series'
  tag = 'tags'
  capability = 'capabilities'
  community = 'communities'
  stage = 'stages'

[params]
  builtBy = "bool"
  defaultImage = "community.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = ""
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = ""

  custom_css = ["css/custom.css"]

  [params.analytics]
    type="UA"
    trackingID = ""

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"
